name: Cybersecurity Chatbot CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore MYCHAT.csproj
      - name: Build
        run: dotnet build MYCHAT.csproj --no-restore
      - name: Check and fix code formatting
        run: dotnet format MYCHAT.csproj # Removed --verify-no-changes
